spring:
  ldap:
    urls: ldap://localhost:10389
    base: dc=planetexpress,dc=com
    username: cn=admin,dc=planetexpress,dc=com
    password: GoodNewsEveryone
  data:
    ldap:
      repositories:
        enabled: true

  config:
    activate:
      on-profile: dev

  datasource:
        # jdbc-url: jdbc:log4jdbc:mariadb://58.225.23.7:3307/albeepoint?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
        jdbc-url: jdbc:mariadb://localhost:3307/albeepoint?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
        username: albeepoint
        password: dba3048!01
        driver-class-name: org.mariadb.jdbc.Driver

        #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 8280

