spring:
  ldap:
#    urls: ldap://localhost:10389
#    base: dc=planetexpress,dc=com
#    username: cn=admin,dc=planetexpress,dc=com
#    password: GoodNewsEveryone
    urls: ldap://192.168.1.101:389
    base: dc=albee,dc=com
    username: Administrator@albee.com
    password: dba3048!01
  data:
    ldap:
      repositories:
        enabled: true

  config:
    activate:
      on-profile: dev

  datasource:
        # jdbc-url: jdbc:log4jdbc:mariadb://58.225.23.7:3307/albeepoint?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
        jdbc-url: jdbc:mariadb://localhost:3307/albeepoint?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=UTC
        username: albeepoint
        password: dba3048!01
        driver-class-name: org.mariadb.jdbc.Driver

        #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

server:
  port: 8280

winrm:
  host: 192.168.1.101
  port: 5985
  username: FileShareAdmin
  password: dba3048!01
  timeout: 60000

ssh:
  host: 192.168.1.101
  port: 22
  username: FileShareAdmin
  password: dba3048!01
  timeout: 60000
  sleeptime: 1000

